# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 246c5f3edf22a62cc6128d84eea43723ea1191a54974388f38cbe87563294ef3fc158e7cb75615cc5f0a98daee0b17704e988ffba8c835feb7cd166e5efe1d2f

test:
  secret_key_base: c3f72edace52b34b3c200896031be732baed8b9edd2ff0f4d0ff4af4dec42bb301a20037fee049fa8f56424e6b06934abc2434bc3351efc49c0dc9376f6f0d06

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
